"""Public contracts for the pure 不羡仙 deterministic domain kernel."""

from buxianxian.domain.character_creation import (
    APTITUDE_OPTION_COUNT,
    TRAIT_OPTION_COUNT,
    AptitudeOption,
    CandidateGenerationResult,
    CandidatesGenerated,
    CharacterConfirmationResult,
    CharacterCreationCandidates,
    CharacterCreationConfirmed,
    CharacterCreationErrorCode,
    CharacterCreationRejected,
    TraitDefinition,
    confirm_character_creation,
    generate_character_creation_candidates,
)
from buxianxian.domain.cultivation import (
    MAX_SEEK_WHEEL_DAYS,
    MIN_SEEK_WHEEL_DAYS,
    WHEEL_SUSPECTED_SIGHTING_THRESHOLD,
    CultivationStage,
    CultivationState,
    SeekWheel,
    WheelSeekingCompleted,
    WheelSeekingDailySettlement,
    WheelSeekingStatus,
    settle_wheel_seeking_day,
)
from buxianxian.domain.engine import DomainEngine
from buxianxian.domain.model import (
    MAX_ADVANCE_DAYS,
    MAX_CHARACTER_NAME_LENGTH,
    MAX_ELAPSED_DAYS,
    TRAIT_SELECTION_COUNT,
    Accepted,
    AdvanceTime,
    Command,
    DomainEvent,
    GameState,
    InnateAptitudes,
    PlayerCharacter,
    Rejected,
    RejectionReason,
    TimeAdvanced,
    TransitionResult,
)
from buxianxian.domain.random_source import RandomSource

__all__ = [
    "APTITUDE_OPTION_COUNT",
    "MAX_ADVANCE_DAYS",
    "MAX_CHARACTER_NAME_LENGTH",
    "MAX_ELAPSED_DAYS",
    "MAX_SEEK_WHEEL_DAYS",
    "MIN_SEEK_WHEEL_DAYS",
    "TRAIT_OPTION_COUNT",
    "TRAIT_SELECTION_COUNT",
    "WHEEL_SUSPECTED_SIGHTING_THRESHOLD",
    "Accepted",
    "AdvanceTime",
    "AptitudeOption",
    "CandidateGenerationResult",
    "CandidatesGenerated",
    "CharacterConfirmationResult",
    "CharacterCreationCandidates",
    "CharacterCreationConfirmed",
    "CharacterCreationErrorCode",
    "CharacterCreationRejected",
    "Command",
    "CultivationStage",
    "CultivationState",
    "DomainEngine",
    "DomainEvent",
    "GameState",
    "InnateAptitudes",
    "PlayerCharacter",
    "RandomSource",
    "Rejected",
    "RejectionReason",
    "SeekWheel",
    "TimeAdvanced",
    "TraitDefinition",
    "TransitionResult",
    "WheelSeekingCompleted",
    "WheelSeekingDailySettlement",
    "WheelSeekingStatus",
    "confirm_character_creation",
    "generate_character_creation_candidates",
    "settle_wheel_seeking_day",
]
