"""Public contracts for headless application orchestration."""

from buxianxian.application.game_runtime import (
    DraftCreated,
    DraftCreationFailed,
    DraftCreationResult,
    DraftNotFound,
    GameLoaded,
    GameLoadFailed,
    GameLoadResult,
    NoActiveSession,
    RuntimeCommandResult,
    RuntimeNewGameResult,
    RuntimeStatus,
    SaveInspectionFailed,
    SaveOverwriteRequired,
    SingleGameRuntime,
)
from buxianxian.application.new_game import (
    CharacterCreationDraft,
    CharacterCreationPreparationFailed,
    CharacterCreationPreparationResult,
    CharacterCreationPrepared,
    InitialSaveFailed,
    NewGameConfirmationResult,
    NewGameCreated,
    NewGameRejected,
    NewGameService,
)
from buxianxian.application.ports import (
    DraftIdentifierSource,
    LoadedSession,
    PersistenceError,
    SessionRepository,
    SingleSaveRepository,
    TransactionalRandomSource,
    TransactionalRandomSourceFactory,
)
from buxianxian.application.session import (
    CommandRejected,
    CommitSucceeded,
    PersistenceFailed,
    PersistentGameSession,
    RevisionConflict,
    SessionResult,
)

__all__ = [
    "CharacterCreationDraft",
    "CharacterCreationPreparationFailed",
    "CharacterCreationPreparationResult",
    "CharacterCreationPrepared",
    "CommandRejected",
    "CommitSucceeded",
    "DraftCreated",
    "DraftCreationFailed",
    "DraftCreationResult",
    "DraftIdentifierSource",
    "DraftNotFound",
    "GameLoadFailed",
    "GameLoadResult",
    "GameLoaded",
    "InitialSaveFailed",
    "LoadedSession",
    "NewGameConfirmationResult",
    "NewGameCreated",
    "NewGameRejected",
    "NewGameService",
    "NoActiveSession",
    "PersistenceError",
    "PersistenceFailed",
    "PersistentGameSession",
    "RevisionConflict",
    "RuntimeCommandResult",
    "RuntimeNewGameResult",
    "RuntimeStatus",
    "SaveInspectionFailed",
    "SaveOverwriteRequired",
    "SessionRepository",
    "SessionResult",
    "SingleGameRuntime",
    "SingleSaveRepository",
    "TransactionalRandomSource",
    "TransactionalRandomSourceFactory",
]
